---
title: "Consolidated NEON Data Grab"
output:
  html_document:
    df_print: paged
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(eval = FALSE)
```

```{r}
#install.packages("neonUtilities")
#install.packages("here")

library(tidyverse)
library(neonUtilities)
library(here)
```

# Set NEON data products, sites, & dates
```{r}
# Fish sampled
water_fishes <- "DP1.20107.001"

# Macroinvertebrates sampled
water_macroinvertebrates <- "DP1.20120.001"

# Water temperature
site_temperatures <- "DP1.20053.001"

# Focal sites
my_sites <- c("MAYF", "BIGC", "KING", "MCDI","TECR", "ARIK", "WLOU", "LECO", "WALK", "LEWI", "POSE", "CRAM", "LIRO")

# Start date (as YYYY-MM)
start_date <- NA #"2020-01"

# End date (as YYYY-MM)
end_date <- NA #"2021-11"

```

# Fish data download
```{r}
list2env((loadByProduct(dpID = water_fishes, 
                        site = my_sites, 
                        include.provisional = TRUE,
                        startdate = start_date,
                        enddate = end_date)),
         .GlobalEnv)
```

```{r}
variables_20107 %>% 
  write_csv(here("data", "raw", "variables_20107.csv"))

fsh_perFish %>%
  write_csv(here("data", "raw", "fsh_perFish.csv"))
```

# Macroinvertebrate data download
```{r}
list2env((loadByProduct(dpID = water_macroinvertebrates, 
                        site = my_sites, 
                        include.provisional = TRUE,
                        startdate = start_date,
                        enddate = end_date)),
         .GlobalEnv)
```

```{r}
variables_20120 %>% 
  write_csv(here("data", "raw", "variables_20120.csv"))

inv_taxonomyProcessed %>% 
  write_csv(here("data", "raw", "inv_taxonomyProcessed.csv"))
```

# Water temperature data download
```{r}
list2env((loadByProduct(dpID = site_temperatures, 
                        site = my_sites, 
                        include.provisional = TRUE,
                        startdate = start_date,
                        enddate = end_date)),
         .GlobalEnv)
```
```{r}
variables_20053 %>% 
  write_csv(here("data", "raw", "variables_20053.csv"))

TSW_30min %>% 
  write_csv(here("data", "raw", "TSW_30min.csv"))
```
