# Fish data wrangling:

## Load required packages.

```{r}
# Load the tidyverse package
library(tidyverse)
library(here)

```

## Create "fish" object.

```{r}

fish <- read.csv(here("data", "raw", "fsh_perFish.csv"))

str(fish)
```

## Select focal data for fish.

```{r}


fish_select <- fish %>% 
  select(taxonID, siteID, scientificName, passStartTime, passEndTime)
```

## Separate fish diversity by month from other data.

```{r}


fish_by_month <- fish_select %>% 
  mutate(month = month(passEndTime),
         year = year(passEndTime)) %>% 
  distinct(taxonID, .keep_all = TRUE) %>% 
  group_by(siteID, year, month) %>% 
  summarize(fish_by_month = unique(n()))

print(fish_by_month) 
```

## write fish_by_month as a separate .csv

```{r}

write_csv(fish_by_month, here("data", "processed", "fish_by_month.csv"))
```

# Macroinvertebrate data wrangling:

## Read macroinvertebrate data.

```{r}
macro_raw <- read_csv(here("data", "raw", "inv_taxonomyProcessed.csv")) 
str(macro_raw)
names(macro_raw)
```

## Select raw data.

```{r}
macro <- macro_raw %>% 
  select(acceptedTaxonID, collectDate, siteID)
```

## Separate data to get macroinvertebrate data by month.

```{r}
 macro_by_month <- macro %>% 
  mutate(month = month(collectDate),
         year = year(collectDate)) %>%
  distinct(acceptedTaxonID, .keep_all = TRUE) %>% 
  group_by(siteID, year, month) %>% 
summarize(macro_by_month = unique(n()))

print(macro_by_month)

```
