```{r}
library(tidyverse)
library(here)
```

## Read macroinvert data.
```{r}
macro_raw <- read_csv(here("data", "raw", "inv_taxonomyProcessed.csv")) 
str(macro_raw)
names(macro_raw)
```

## Select raw data.
```{r}
macro <- macro_raw %>% 
  select(acceptedTaxonID, collectDate, siteID)
```

## Separate data to get macroinvertebrate data by month.
```{r}
 macro_by_month <- macro %>% 
  mutate(month = month(collectDate),
         year = year(collectDate)) %>%
  distinct(acceptedTaxonID, .keep_all = TRUE) %>% 
  group_by(siteID, year, month) %>% 
summarize(macro_by_month = unique(n()))

print(macro_by_month)

```
# Sort by season, not month to get better data feedback
```{r}
macro_by_month <- macro %>%
  mutate(month = month(collectDate),
         year = year(collectDate),
         siteID = factor(siteID),
         season = factor(ifelse(month %in% c(3,4,5), "spring",
                         ifelse(month %in% c(6,7,8), "summer",
                                ifelse(month %in% c(9,10,11), "fall", "winter"))))) %>%
  group_by(siteID, season, year, month) %>%
  summarize(unique_taxa = n_distinct(acceptedTaxonID))
print(macro_by_month)

 
```
#Use an ANOVA test to find correlation between unique species and season for each site

```{r}
#macro_by_month_MAYF <- macro_by_month %>%
#filter(siteID == "MAYF")

unique_taxa_aov <- aov(unique_taxa ~ season * siteID, data = macro_by_month)

summary(unique_taxa_aov)

# Additive Model
unique_taxa_aov2 <- aov(unique_taxa ~ season + siteID, data = macro_by_month)

summary(unique_taxa_aov2)

```

```{r}

ggplot(macro_by_month,
       aes(x = season,
           y = unique_taxa,
           fill = siteID)) +
  geom_boxplot() +
  theme_bw()

```

